package com.itau.token.validator.domain.token.model;

public enum ConstantsMessageException {
    REGRA_NEGOCIO_NAME_INVALIDO, REGRA_NEGOCIO_TAMANHO_NAME_INVALIDO, QUANTIDADE_CLAIM_INVALIDA, REGRA_NEGOCIO_ROLE_INVALIDA, REGRA_NEGOCIO_SEED_NUMERICO, REGRA_NEGOCIO_SEED_NUMERO_PRIMO, ERRO_EXTRAIR_TOKEN

}
