openapi: 3.0.0
info:
  title: Token Validator Api
  description: API responsável por fazer validações de token jwt
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: http://localhost:1010/v1
    description: Local development server
paths:
  /v1/validacao/token:
    post:
      tags:
        - Valida Token
      operationId: validaToken
      summary: Valida Token
      description: Endpoint responsável por fazer a validação do token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
      responses:
        '200':
          description: Token validado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: Token Invalido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardErrorResponse'
        '422':
          description: Token Invalido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'

components:
  schemas:
    TokenRequest:
      type: object
      description: objeto de request para validacao de token
      required:
        - tokenJwt
      properties:
        tokenJwt:
          type: string
          pattern: '[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+'
          description: campo deverá conter o token jwt para validação
          example: "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJTZWVkIjoiNzg0MSIsIk5hbWUiOiJUb25pbmhvIEFyYXVqbyJ9.QY05sIjtrcJnP533kQNk8QXcaleJ1Q01jWY_ZzIZuAg"
    StandardErrorResponse:
      type: object
      description: objeto de retorno para cenários de exception
      properties:
        message:
          type: string
          example: "Token invalido"
        timeStamp:
          type: string
          format: date-time
          example: 2017-07-21T17:32:28Z
    FieldMessage:
      type: object
      properties:
        fieldName:
          type: string
        message:
          type: string
    ValidationError:
      type: object
      properties:
        mensagem:
          type: string
          example: campos tokenJwt invalido
        timeStamp:
          type: string
          format: date-time
        errors:
          type: array
          items:
            $ref: '#/components/schemas/FieldMessage'
    TokenResponse:
      type: object
      description: objeto de retorno para cenários sucesso na validacao do token
      properties:
        valido:
          type: boolean
          description: propriedade responsável por dizer se o token foi validado com sucesso, em caso de validaçao com sucesso retorna true em caso contrário retorna false
          example: true