spring:
  application:
    name: token-validator

server:
  port: 8080


management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
#springdoc:
#  pathsToMatch: /**
#  swagger-ui:
#    enabled: true
